version: "3.7"
services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pollsweb
    ports:
      - "5432:5432"